In [2]:
pip install ucimlrepo

Collecting ucimlrepo
  Downloading ucimlrepo-0.0.7-py3-none-any.whl.metadata (5.5 kB)
Requirement already satisfied: pandas>=1.0.0 in c:\users\limin\anaconda3\lib\site-packages (from ucimlrepo) (2.2.2)
Requirement already satisfied: certifi>=2020.12.5 in c:\users\limin\anaconda3\lib\site-packages (from ucimlrepo) (2024.8.30)
Requirement already satisfied: numpy>=1.26.0 in c:\users\limin\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (1.26.4)
Requirement already satisfied: python-dateutil>=2.8.2 in c:\users\limin\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2.9.0.post0)
Requirement already satisfied: pytz>=2020.1 in c:\users\limin\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2024.1)
Requirement already satisfied: tzdata>=2022.7 in c:\users\limin\anaconda3\lib\site-packages (from pandas>=1.0.0->ucimlrepo) (2023.3)
Requirement already satisfied: six>=1.5 in c:\users\limin\anaconda3\lib\site-packages (from python-dateutil>=2.8.2->pandas>=1.0.0->ucimlrepo) (1.16.0)
Downloading ucimlrepo-0.0.7-py3-none-any.whl (8.0 kB)
Installing collected packages: ucimlrepo
Successfully installed ucimlrepo-0.0.7
Note: you may need to restart the kernel to use updated packages.

In [3]:
from ucimlrepo import fetch_ucirepo 
  
# fetch dataset 
diabetes_130_us_hospitals_for_years_1999_2008 = fetch_ucirepo(id=296) 
  
# data (as pandas dataframes) 
X = diabetes_130_us_hospitals_for_years_1999_2008.data.features 
y = diabetes_130_us_hospitals_for_years_1999_2008.data.targets 
  
# metadata 
print(diabetes_130_us_hospitals_for_years_1999_2008.metadata) 
  
# variable information 
print(diabetes_130_us_hospitals_for_years_1999_2008.variables)

c:\Users\limin\anaconda3\Lib\site-packages\ucimlrepo\fetch.py:97: DtypeWarning: Columns (10) have mixed types. Specify dtype option on import or set low_memory=False.
  df = pd.read_csv(data_url)

{'uci_id': 296, 'name': 'Diabetes 130-US Hospitals for Years 1999-2008', 'repository_url': 'https://archive.ics.uci.edu/dataset/296/diabetes+130-us+hospitals+for+years+1999-2008', 'data_url': 'https://archive.ics.uci.edu/static/public/296/data.csv', 'abstract': 'The dataset represents ten years (1999-2008) of clinical care at 130 US hospitals and integrated delivery networks. Each row concerns hospital records of patients diagnosed with diabetes, who underwent laboratory, medications, and stayed up to 14 days. The goal is to determine the early readmission of the patient within 30 days of discharge.\nThe problem is important for the following reasons. Despite high-quality evidence showing improved clinical outcomes for diabetic patients who receive various preventive and therapeutic interventions, many patients do not receive them. This can be partially attributed to arbitrary diabetes management in hospital environments, which fail to attend to glycemic control. Failure to provide proper diabetes care not only increases the managing costs for the hospitals (as the patients are readmitted) but also impacts the morbidity and mortality of the patients, who may face complications associated with diabetes.\n', 'area': 'Health and Medicine', 'tasks': ['Classification', 'Clustering'], 'characteristics': ['Multivariate'], 'num_instances': 101766, 'num_features': 47, 'feature_types': ['Categorical', 'Integer'], 'demographics': ['Race', 'Gender', 'Age'], 'target_col': ['readmitted'], 'index_col': ['encounter_id', 'patient_nbr'], 'has_missing_values': 'yes', 'missing_values_symbol': 'NaN', 'year_of_dataset_creation': 2014, 'last_updated': 'Tue Sep 24 2024', 'dataset_doi': '10.24432/C5230J', 'creators': ['John Clore', 'Krzysztof Cios', 'Jon DeShazo', 'Beata Strack'], 'intro_paper': {'ID': 225, 'type': 'NATIVE', 'title': 'Impact of HbA1c Measurement on Hospital Readmission Rates: Analysis of 70,000 Clinical Database Patient Record', 'authors': 'Beata Strack, Jonathan DeShazo, Chris Gennings, Juan Olmo, Sebastian Ventura, Krzysztof Cios, John Clore', 'venue': 'BioMed Research International, vol. 2014', 'year': 2014, 'journal': None, 'DOI': None, 'URL': 'https://www.hindawi.com/journals/bmri/2014/781670/', 'sha': None, 'corpus': None, 'arxiv': None, 'mag': None, 'acl': None, 'pmid': None, 'pmcid': None}, 'additional_info': {'summary': 'The dataset represents ten years (1999-2008) of clinical care at 130 US hospitals and integrated delivery networks. It includes over 50 features representing patient and hospital outcomes. Information was extracted from the database for encounters that satisfied the following criteria.\n(1)\tIt is an inpatient encounter (a hospital admission).\n(2)\tIt is a diabetic encounter, that is, one during which any kind of diabetes was entered into the system as a diagnosis.\n(3)\tThe length of stay was at least 1 day and at most 14 days.\n(4)\tLaboratory tests were performed during the encounter.\n(5)\tMedications were administered during the encounter.\n\nThe data contains such attributes as patient number, race, gender, age, admission type, time in hospital, medical specialty of admitting physician, number of lab tests performed, HbA1c test result, diagnosis, number of medications, diabetic medications, number of outpatient, inpatient, and emergency visits in the year before the hospitalization, etc.', 'purpose': None, 'funded_by': None, 'instances_represent': 'The instances represent hospitalized patient records diagnosed with diabetes.', 'recommended_data_splits': 'No recommendation. The standard train-test split could be used. Can use three-way holdout split (i.e., train-validation-test) when doing model selection.', 'sensitive_data': 'Yes. The dataset contains information about the age, gender, and race of the patients.', 'preprocessing_description': None, 'variable_info': 'Detailed description of all the atrributes is provided in Table 1 Beata Strack, Jonathan P. DeShazo, Chris Gennings,  Juan L. Olmo, Sebastian Ventura,  Krzysztof J. Cios, and John N. Clore, “Impact of HbA1c Measurement on Hospital Readmission Rates: Analysis of 70,000 Clinical Database Patient Records,” BioMed Research International, vol. 2014, Article ID 781670, 11 pages, 2014.\n\nhttp://www.hindawi.com/journals/bmri/2014/781670/', 'citation': 'Please cite:\nBeata Strack, Jonathan P. DeShazo, Chris Gennings, Juan L. Olmo, Sebastian Ventura, Krzysztof J. Cios, and John N. Clore, “Impact of HbA1c Measurement on Hospital Readmission Rates: Analysis of 70,000 Clinical Database Patient Records,” BioMed Research International, vol. 2014, Article ID 781670, 11 pages, 2014.'}}
                        name     role         type demographic  \
0               encounter_id       ID                     None
1                patient_nbr       ID                     None
2                       race  Feature  Categorical        Race
3                     gender  Feature  Categorical      Gender
4                        age  Feature  Categorical         Age
5                     weight  Feature  Categorical        None
6          admission_type_id  Feature  Categorical        None
7   discharge_disposition_id  Feature  Categorical        None
8        admission_source_id  Feature  Categorical        None
9           time_in_hospital  Feature      Integer        None
10                payer_code  Feature  Categorical        None
11         medical_specialty  Feature  Categorical        None
12        num_lab_procedures  Feature      Integer        None
13            num_procedures  Feature      Integer        None
14           num_medications  Feature      Integer        None
15         number_outpatient  Feature      Integer        None
16          number_emergency  Feature      Integer        None
17          number_inpatient  Feature      Integer        None
18                    diag_1  Feature  Categorical        None
19                    diag_2  Feature  Categorical        None
20                    diag_3  Feature  Categorical        None
21          number_diagnoses  Feature      Integer        None
22             max_glu_serum  Feature  Categorical        None
23                 A1Cresult  Feature  Categorical        None
24                 metformin  Feature  Categorical        None
25               repaglinide  Feature  Categorical        None
26               nateglinide  Feature  Categorical        None
27            chlorpropamide  Feature  Categorical        None
28               glimepiride  Feature  Categorical        None
29             acetohexamide  Feature  Categorical        None
30                 glipizide  Feature  Categorical        None
31                 glyburide  Feature  Categorical        None
32               tolbutamide  Feature  Categorical        None
33              pioglitazone  Feature  Categorical        None
34             rosiglitazone  Feature  Categorical        None
35                  acarbose  Feature  Categorical        None
36                  miglitol  Feature  Categorical        None
37              troglitazone  Feature  Categorical        None
38                tolazamide  Feature  Categorical        None
39                   examide  Feature  Categorical        None
40               citoglipton  Feature  Categorical        None
41                   insulin  Feature  Categorical        None
42       glyburide-metformin  Feature  Categorical        None
43       glipizide-metformin  Feature  Categorical        None
44  glimepiride-pioglitazone  Feature  Categorical        None
45   metformin-rosiglitazone  Feature  Categorical        None
46    metformin-pioglitazone  Feature  Categorical        None
47                    change  Feature  Categorical        None
48               diabetesMed  Feature  Categorical        None
49                readmitted   Target  Categorical        None

                                          description units missing_values
0                   Unique identifier of an encounter  None             no
1                      Unique identifier of a patient  None             no
2   Values: Caucasian, Asian, African American, Hi...  None            yes
3           Values: male, female, and unknown/invalid  None             no
4   Grouped in 10-year intervals: [0, 10), [10, 20...  None             no
5                                   Weight in pounds.  None            yes
6   Integer identifier corresponding to 9 distinct...  None             no
7   Integer identifier corresponding to 29 distinc...  None             no
8   Integer identifier corresponding to 21 distinc...  None             no
9   Integer number of days between admission and d...  None             no
10  Integer identifier corresponding to 23 distinc...  None            yes
11  Integer identifier of a specialty of the admit...  None            yes
12  Number of lab tests performed during the encou...  None             no
13  Number of procedures (other than lab tests) pe...  None             no
14  Number of distinct generic names administered ...  None             no
15  Number of outpatient visits of the patient in ...  None             no
16  Number of emergency visits of the patient in t...  None             no
17  Number of inpatient visits of the patient in t...  None             no
18  The primary diagnosis (coded as first three di...  None            yes
19  Secondary diagnosis (coded as first three digi...  None            yes
20  Additional secondary diagnosis (coded as first...  None            yes
21          Number of diagnoses entered to the system  None             no
22  Indicates the range of the result or if the te...  None             no
23  Indicates the range of the result or if the te...  None             no
24  The feature indicates whether the drug was pre...  None             no
25  The feature indicates whether the drug was pre...  None             no
26  The feature indicates whether the drug was pre...  None             no
27  The feature indicates whether the drug was pre...  None             no
28  The feature indicates whether the drug was pre...  None             no
29  The feature indicates whether the drug was pre...  None             no
30  The feature indicates whether the drug was pre...  None             no
31  The feature indicates whether the drug was pre...  None             no
32  The feature indicates whether the drug was pre...  None             no
33  The feature indicates whether the drug was pre...  None             no
34  The feature indicates whether the drug was pre...  None             no
35  The feature indicates whether the drug was pre...  None             no
36  The feature indicates whether the drug was pre...  None             no
37  The feature indicates whether the drug was pre...  None             no
38  The feature indicates whether the drug was pre...  None             no
39  The feature indicates whether the drug was pre...  None             no
40  The feature indicates whether the drug was pre...  None             no
41  The feature indicates whether the drug was pre...  None             no
42  The feature indicates whether the drug was pre...  None             no
43  The feature indicates whether the drug was pre...  None             no
44  The feature indicates whether the drug was pre...  None             no
45  The feature indicates whether the drug was pre...  None             no
46  The feature indicates whether the drug was pre...  None             no
47  Indicates if there was a change in diabetic me...  None             no
48  Indicates if there was any diabetic medication...  None             no
49  Days to inpatient readmission. Values: <30 if ...  None             no

In [5]:
import numpy as np 
import pandas as pd
import matplotlib.pyplot as plt
import seaborn as sns

it is possible to determine the dimensions of a dataset by looking at the shape of a pandas DataFrame, the functio returns a tuple consisting of two elements 
(Tuple is an immutable and ordered collection of elemens in python, used to store multiple items in a single variable, simillar to lists):
-Dataset rows: the number of observations of patients
-The number of columns: indicsates the amount of features or attriubutes each patient has

What are the benefits of shape?
-A dataset's SIZE indicates how big it is
-COMPLEXITY: the number of features that need to be analyzed or cleaned

What is the value if information?
    - **Overview of the dataset**: It immediately tells us how many entries we are analysing, which is crucial for understanding its scope.
    - **Memory and performance**: Knowing the shape helps us estimate the processing resources required.
    - **Validation of data**: Ensures datasets have the expected number of observations and features (for example, if a dataset should have 10 features but has 15, it indicates a problem).
    - **Feature complexity**: The number of features that require analysis or cleaning.

In [16]:
df = pd.read_csv(r"C:\Users\limin\OneDrive\Documenten\Block B\diabetic_data.csv")
print(df)

        encounter_id  patient_nbr             race  gender      age weight  \
0            2278392      8222157        Caucasian  Female   [0-10)      ?
1             149190     55629189        Caucasian  Female  [10-20)      ?
2              64410     86047875  AfricanAmerican  Female  [20-30)      ?
3             500364     82442376        Caucasian    Male  [30-40)      ?
4              16680     42519267        Caucasian    Male  [40-50)      ?
...              ...          ...              ...     ...      ...    ...
101761     443847548    100162476  AfricanAmerican    Male  [70-80)      ?
101762     443847782     74694222  AfricanAmerican  Female  [80-90)      ?
101763     443854148     41088789        Caucasian    Male  [70-80)      ?
101764     443857166     31693671        Caucasian  Female  [80-90)      ?
101765     443867222    175429310        Caucasian    Male  [70-80)      ?

        admission_type_id  discharge_disposition_id  admission_source_id  \
0                       6                        25                    1
1                       1                         1                    7
2                       1                         1                    7
3                       1                         1                    7
4                       1                         1                    7
...                   ...                       ...                  ...
101761                  1                         3                    7
101762                  1                         4                    5
101763                  1                         1                    7
101764                  2                         3                    7
101765                  1                         1                    7

        time_in_hospital  ... citoglipton insulin  glyburide-metformin  \
0                      1  ...          No      No                   No
1                      3  ...          No      Up                   No
2                      2  ...          No      No                   No
3                      2  ...          No      Up                   No
4                      1  ...          No  Steady                   No
...                  ...  ...         ...     ...                  ...
101761                 3  ...          No    Down                   No
101762                 5  ...          No  Steady                   No
101763                 1  ...          No    Down                   No
101764                10  ...          No      Up                   No
101765                 6  ...          No      No                   No

        glipizide-metformin  glimepiride-pioglitazone  \
0                        No                        No
1                        No                        No
2                        No                        No
3                        No                        No
4                        No                        No
...                     ...                       ...
101761                   No                        No
101762                   No                        No
101763                   No                        No
101764                   No                        No
101765                   No                        No

        metformin-rosiglitazone  metformin-pioglitazone  change diabetesMed  \
0                            No                      No      No          No
1                            No                      No      Ch         Yes
2                            No                      No      No         Yes
3                            No                      No      Ch         Yes
4                            No                      No      Ch         Yes
...                         ...                     ...     ...         ...
101761                       No                      No      Ch         Yes
101762                       No                      No      No         Yes
101763                       No                      No      Ch         Yes
101764                       No                      No      Ch         Yes
101765                       No                      No      No          No

       readmitted
0              NO
1             >30
2              NO
3              NO
4              NO
...           ...
101761        >30
101762         NO
101763         NO
101764         NO
101765         NO

[101766 rows x 50 columns]

In [13]:
rows, cols = df.shape
print(f"rows: {rows}, columns: {cols}")

rows: 101766, columns: 50

In [17]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 101766 entries, 0 to 101765
Data columns (total 50 columns):
 #   Column                    Non-Null Count   Dtype
---  ------                    --------------   -----
 0   encounter_id              101766 non-null  int64
 1   patient_nbr               101766 non-null  int64
 2   race                      101766 non-null  object
 3   gender                    101766 non-null  object
 4   age                       101766 non-null  object
 5   weight                    101766 non-null  object
 6   admission_type_id         101766 non-null  int64
 7   discharge_disposition_id  101766 non-null  int64
 8   admission_source_id       101766 non-null  int64
 9   time_in_hospital          101766 non-null  int64
 10  payer_code                101766 non-null  object
 11  medical_specialty         101766 non-null  object
 12  num_lab_procedures        101766 non-null  int64
 13  num_procedures            101766 non-null  int64
 14  num_medications           101766 non-null  int64
 15  number_outpatient         101766 non-null  int64
 16  number_emergency          101766 non-null  int64
 17  number_inpatient          101766 non-null  int64
 18  diag_1                    101766 non-null  object
 19  diag_2                    101766 non-null  object
 20  diag_3                    101766 non-null  object
 21  number_diagnoses          101766 non-null  int64
 22  max_glu_serum             5346 non-null    object
 23  A1Cresult                 17018 non-null   object
 24  metformin                 101766 non-null  object
 25  repaglinide               101766 non-null  object
 26  nateglinide               101766 non-null  object
 27  chlorpropamide            101766 non-null  object
 28  glimepiride               101766 non-null  object
 29  acetohexamide             101766 non-null  object
 30  glipizide                 101766 non-null  object
 31  glyburide                 101766 non-null  object
 32  tolbutamide               101766 non-null  object
 33  pioglitazone              101766 non-null  object
 34  rosiglitazone             101766 non-null  object
 35  acarbose                  101766 non-null  object
 36  miglitol                  101766 non-null  object
 37  troglitazone              101766 non-null  object
 38  tolazamide                101766 non-null  object
 39  examide                   101766 non-null  object
 40  citoglipton               101766 non-null  object
 41  insulin                   101766 non-null  object
 42  glyburide-metformin       101766 non-null  object
 43  glipizide-metformin       101766 non-null  object
 44  glimepiride-pioglitazone  101766 non-null  object
 45  metformin-rosiglitazone   101766 non-null  object
 46  metformin-pioglitazone    101766 non-null  object
 47  change                    101766 non-null  object
 48  diabetesMed               101766 non-null  object
 49  readmitted                101766 non-null  object
dtypes: int64(13), object(37)
memory usage: 38.8+ MB

In [18]:
df.describe()

,encounter_id,patient_nbr,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,num_lab_procedures,num_procedures,num_medications,number_outpatient,number_emergency,number_inpatient,number_diagnoses
count,101766.00,101766.00,101766.00,101766.00,101766.00,101766.00,101766.00,101766.00,101766.00,101766.00,101766.00,101766.00,101766.00
mean,165201645.62,54330400.69,2.02,3.72,5.75,4.40,43.10,1.34,16.02,0.37,0.20,0.64,7.42
std,102640295.98,38696359.35,1.45,5.28,4.06,2.99,19.67,1.71,8.13,1.27,0.93,1.26,1.93
min,12522.00,135.00,1.00,1.00,1.00,1.00,1.00,0.00,1.00,0.00,0.00,0.00,1.00
25%,84961194.00,23413221.00,1.00,1.00,1.00,2.00,31.00,0.00,10.00,0.00,0.00,0.00,6.00
50%,152388987.00,45505143.00,1.00,1.00,7.00,4.00,44.00,1.00,15.00,0.00,0.00,0.00,8.00
75%,230270887.50,87545949.75,3.00,4.00,7.00,6.00,57.00,2.00,20.00,0.00,0.00,1.00,9.00
max,443867222.00,189502619.00,8.00,28.00,25.00,14.00,132.00,6.00,81.00,42.00,76.00,21.00,16.00

In [19]:
df.isnull().sum()

encounter_id                    0
patient_nbr                     0
race                            0
gender                          0
age                             0
weight                          0
admission_type_id               0
discharge_disposition_id        0
admission_source_id             0
time_in_hospital                0
payer_code                      0
medical_specialty               0
num_lab_procedures              0
num_procedures                  0
num_medications                 0
number_outpatient               0
number_emergency                0
number_inpatient                0
diag_1                          0
diag_2                          0
diag_3                          0
number_diagnoses                0
max_glu_serum               96420
A1Cresult                   84748
metformin                       0
repaglinide                     0
nateglinide                     0
chlorpropamide                  0
glimepiride                     0
acetohexamide                   0
glipizide                       0
glyburide                       0
tolbutamide                     0
pioglitazone                    0
rosiglitazone                   0
acarbose                        0
miglitol                        0
troglitazone                    0
tolazamide                      0
examide                         0
citoglipton                     0
insulin                         0
glyburide-metformin             0
glipizide-metformin             0
glimepiride-pioglitazone        0
metformin-rosiglitazone         0
metformin-pioglitazone          0
change                          0
diabetesMed                     0
readmitted                      0
dtype: int64

In [20]:
df.nunique()

encounter_id                101766
patient_nbr                  71518
race                             6
gender                           3
age                             10
weight                          10
admission_type_id                8
discharge_disposition_id        26
admission_source_id             17
time_in_hospital                14
payer_code                      18
medical_specialty               73
num_lab_procedures             118
num_procedures                   7
num_medications                 75
number_outpatient               39
number_emergency                33
number_inpatient                21
diag_1                         717
diag_2                         749
diag_3                         790
number_diagnoses                16
max_glu_serum                    3
A1Cresult                        3
metformin                        4
repaglinide                      4
nateglinide                      4
chlorpropamide                   4
glimepiride                      4
acetohexamide                    2
glipizide                        4
glyburide                        4
tolbutamide                      2
pioglitazone                     4
rosiglitazone                    4
acarbose                         4
miglitol                         4
troglitazone                     2
tolazamide                       3
examide                          1
citoglipton                      1
insulin                          4
glyburide-metformin              4
glipizide-metformin              2
glimepiride-pioglitazone         2
metformin-rosiglitazone          2
metformin-pioglitazone           2
change                           2
diabetesMed                      2
readmitted                       3
dtype: int64

In [21]:
df

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
0,2278392,8222157,Caucasian,Female,[0-10),?,6,25,1,1,...,No,No,No,No,No,No,No,No,No,NO
1,149190,55629189,Caucasian,Female,[10-20),?,1,1,7,3,...,No,Up,No,No,No,No,No,Ch,Yes,>30
2,64410,86047875,AfricanAmerican,Female,[20-30),?,1,1,7,2,...,No,No,No,No,No,No,No,No,Yes,NO
3,500364,82442376,Caucasian,Male,[30-40),?,1,1,7,2,...,No,Up,No,No,No,No,No,Ch,Yes,NO
4,16680,42519267,Caucasian,Male,[40-50),?,1,1,7,1,...,No,Steady,No,No,No,No,No,Ch,Yes,NO
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
101761,443847548,100162476,AfricanAmerican,Male,[70-80),?,1,3,7,3,...,No,Down,No,No,No,No,No,Ch,Yes,>30
101762,443847782,74694222,AfricanAmerican,Female,[80-90),?,1,4,5,5,...,No,Steady,No,No,No,No,No,No,Yes,NO
101763,443854148,41088789,Caucasian,Male,[70-80),?,1,1,7,1,...,No,Down,No,No,No,No,No,Ch,Yes,NO
101764,443857166,31693671,Caucasian,Female,[80-90),?,2,3,7,10,...,No,Up,No,No,No,No,No,Ch,Yes,NO
101765,443867222,175429310,Caucasian,Male,[70-80),?,1,1,7,6,...,No,No,No,No,No,No,No,No,No,NO

In [24]:
df.sort_values(by='race', ascending=False).head(10)

,encounter_id,patient_nbr,race,gender,age,weight,admission_type_id,discharge_disposition_id,admission_source_id,time_in_hospital,...,citoglipton,insulin,glyburide-metformin,glipizide-metformin,glimepiride-pioglitazone,metformin-rosiglitazone,metformin-pioglitazone,change,diabetesMed,readmitted
30244,97906296,14230044,Other,Male,[40-50),?,1,1,1,3,...,No,No,No,No,No,No,No,Ch,Yes,>30
52153,154718916,100827090,Other,Male,[60-70),?,1,6,7,4,...,No,No,No,No,No,No,No,No,Yes,NO
48374,147687504,41641776,Other,Male,[70-80),?,3,6,1,5,...,No,Steady,No,No,No,No,No,No,Yes,NO
37959,117817230,34248078,Other,Male,[50-60),?,2,1,1,3,...,No,No,No,No,No,No,No,No,Yes,>30
52169,154740618,59878035,Other,Female,[80-90),?,2,1,1,4,...,No,No,No,No,No,No,No,No,No,>30
95984,369067442,146891300,Other,Female,[80-90),?,3,22,1,12,...,No,Steady,No,No,No,No,No,No,Yes,NO
4960,26862408,7258698,Other,Male,[50-60),?,2,6,4,13,...,No,Steady,No,No,No,No,No,No,Yes,>30
90607,297841664,152618450,Other,Female,[40-50),?,1,1,7,6,...,No,No,No,No,No,No,No,No,Yes,NO
1613,10863672,11963232,Other,Female,[70-80),?,1,1,7,4,...,No,Steady,No,No,No,No,No,No,Yes,NO
78570,240159246,71541414,Other,Male,[60-70),?,1,1,7,6,...,No,Steady,No,No,No,No,No,Ch,Yes,>30

In [26]:
sns.heatmap(df.corr(), annot = True)

ValueError: could not convert string to float: 'Caucasian'

In [27]:
print(df.columns)
print(df['age'].head())

Index(['encounter_id', 'patient_nbr', 'race', 'gender', 'age', 'weight',
       'admission_type_id', 'discharge_disposition_id', 'admission_source_id',
       'time_in_hospital', 'payer_code', 'medical_specialty',
       'num_lab_procedures', 'num_procedures', 'num_medications',
       'number_outpatient', 'number_emergency', 'number_inpatient', 'diag_1',
       'diag_2', 'diag_3', 'number_diagnoses', 'max_glu_serum', 'A1Cresult',
       'metformin', 'repaglinide', 'nateglinide', 'chlorpropamide',
       'glimepiride', 'acetohexamide', 'glipizide', 'glyburide', 'tolbutamide',
       'pioglitazone', 'rosiglitazone', 'acarbose', 'miglitol', 'troglitazone',
       'tolazamide', 'examide', 'citoglipton', 'insulin',
       'glyburide-metformin', 'glipizide-metformin',
       'glimepiride-pioglitazone', 'metformin-rosiglitazone',
       'metformin-pioglitazone', 'change', 'diabetesMed', 'readmitted'],
      dtype='object')
0     [0-10)
1    [10-20)
2    [20-30)
3    [30-40)
4    [40-50)
Name: age, dtype: object